import 'bootstrap-icons/font/bootstrap-icons.css';
import 'bootstrap/dist/css/bootstrap.css';
import 'glightbox/dist/css/glightbox.css';
import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import Script from 'next/script';

import TopBar from './components/TopBar';

const playFair = Playfair_Display({
  variable: '--font-playfair-display',
  subsets: ["latin"],
  display: 'swap',
  weight : ['400', '500', '600', '700', '800', '900' ],
});



export const metadata: Metadata = {
  title: "Reataurant booking app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${playFair.variable}`}>
        <TopBar/>
        {children}
      </body>
      <Script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" 
      integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" 
      crossOrigin="anonymous"
      />
    </html>
  );
}
